#ifndef GAME_KEYS_H
#define GAME_KEYS_H

// NOTE(ivan): Keyboard key codes.
enum key_code {
    KeyCode_Enter = 0,
	KeyCode_Tab,
	KeyCode_Escape,
	KeyCode_Space,
	KeyCode_BackSpace,
	KeyCode_LeftShift,
	KeyCode_RightShift,
	KeyCode_LeftAlt,
	KeyCode_RightAlt,
	KeyCode_LeftControl,
	KeyCode_RightControl,
	KeyCode_LeftSuper,
	KeyCode_RightSuper,
	KeyCode_Home,
	KeyCode_End,
	KeyCode_PageUp,
	KeyCode_PageDown,
	KeyCode_Insert,
	KeyCode_Delete,
	KeyCode_Up,
	KeyCode_Down,
	KeyCode_Left,
	KeyCode_Right,

	KeyCode_F1,
	KeyCode_F2,
	KeyCode_F3,
	KeyCode_F4,
	KeyCode_F5,
	KeyCode_F6,
	KeyCode_F7,
	KeyCode_F8,
	KeyCode_F9,
	KeyCode_F10,
	KeyCode_F11,
	KeyCode_F12,

	KeyCode_NumLock,
	KeyCode_CapsLock,
	KeyCode_ScrollLock,

	KeyCode_PrintScreen,
	KeyCode_Pause,

	KeyCode_A,
	KeyCode_B,
	KeyCode_C,
	KeyCode_D,
	KeyCode_E,
	KeyCode_F,
	KeyCode_G,
	KeyCode_H,
	KeyCode_I,
	KeyCode_J,
	KeyCode_K,
	KeyCode_L,
	KeyCode_M,
	KeyCode_N,
	KeyCode_O,
	KeyCode_P,
	KeyCode_Q,
	KeyCode_R,
	KeyCode_S,
	KeyCode_T,
	KeyCode_U,
	KeyCode_V,
	KeyCode_W,
	KeyCode_X,
	KeyCode_Y,
	KeyCode_Z,

	KeyCode_0,
	KeyCode_1,
	KeyCode_2,
	KeyCode_3,
	KeyCode_4,
	KeyCode_5,
	KeyCode_6,
	KeyCode_7,
	KeyCode_8,
	KeyCode_9,

	KeyCode_OpenBracket,
	KeyCode_CloseBracket,
	KeyCode_Semicolon,
	KeyCode_Quote,
	KeyCode_Comma,
	KeyCode_Period,
	KeyCode_Slash,
	KeyCode_BackSlash,
	KeyCode_Tilde,
	KeyCode_Plus,
	KeyCode_Minus,

	KeyCode_NumUp,
	KeyCode_NumDown,
	KeyCode_NumLeft,
	KeyCode_NumRight,
	KeyCode_NumHome,
	KeyCode_NumEnd,
	KeyCode_NumPageUp,
	KeyCode_NumPageDown,
	KeyCode_NumInsert,
	KeyCode_NumDelete,
	KeyCode_NumEnter,
	KeyCode_NumMultiply,
	KeyCode_NumDivide,
	KeyCode_NumPlus,
	KeyCode_NumMinus,
	KeyCode_NumClear,

	KeyCode_MaxCount
};

#endif // #ifndef GAME_KEYS_H
